### ISSUE TITLE
Compiled with problems

### ISSUE THREAD

**Issue by rapomon** [CodelyTV/cra-template-codely#2]
After create the react app with your template and launch npm start, the browser shows the following error:

Compiled with problems:

ERROR

[eslint] package.json » eslint-config-codely/typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/member-ordering" is invalid:
	Value ["signature","public-static-field","protected-static-field","private-static-field","public-decorated-field","protected-decorated-field","private-decorated-field","public-instance-field","protected-instance-field","private-instance-field","public-abstract-field","protected-abstract-field","private-abstract-field","public-constructor","protected-constructor","private-constructor","public-abstract-method","protected-abstract-method","private-abstract-method","public-static-method","protected-static-method","private-static-method","public-decorated-method","protected-decorated-method","private-decorated-method","public-instance-method","protected-instance-method","private-instance-method"] should be string.

**Comment by 0x10-z** [comment]
Same problem here. Node v18.12.1 installed. If you exec npm start, sometimes goes fine even the error appears. But it is impossible to just build.

**Comment by nuria-fl** [comment]
Hi! We have fixed this in [eslint-config-codely](https://github.com/CodelyTV/eslint-config-codely/issues/5). It was caused by a breaking change introduced in a minor version of typescript/eslint: https://github.com/typescript-eslint/typescript-eslint/issues/6132

If you already have a project set up with this template you can fix it by manually upgrading eslint-config-codely to 2.1.2.

Thanks for the report!

**Comment by rapomon** [comment]
Thank you Núria. Soy un gran seguidor de vuestro canal. Seguid así!
